export const data = [
    {
      name: "Warehouse-165",
      code: "W-00001",
      id: 1,
      city: "Delhi",
      space_available: 1234,
      type: "Leasable Space",
      cluster: "cluster-a-32",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-276",
      code: "W-00002",
      id: 2,
      city: "Chennai",
      space_available: 124,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-3039",
      code: "W-00003",
      id: 3,
      city: "Indore",
      space_available: 134,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-324",
      code: "W-00004",
      id: 4,
      city: "Chennai",
      space_available: 12,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-5454",
      code: "W-00005",
      id: 5,
      city: "Chennai",
      space_available: 1243434,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-4345",
      code: "W-00006",
      id: 6,
      city: "Chennai",
      space_available: 1,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-3455",
      code: "W-00007",
      id: 7,
      city: "Mumbai",
      space_available: 4,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-23455",
      code: "W-00008",
      id: 8,
      city: "Bangalore",
      space_available: 3456,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-6457",
      code: "W-00009",
      id: 9,
      city: "Bangalore",
      space_available: 1234545,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-32456",
      code: "W-000010",
      id: 10,
      city: "Guwahati",
      space_available: 121234,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-3245678",
      code: "W-000011",
      id: 11,
      city: "Delhi",
      space_available: 98,
      type: "Leasable Space",
      cluster: "cluster-v-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-4567",
      code: "W-000012",
      id: 12,
      city: "Indore",
      space_available: 97,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-458",
      code: "W-000013",
      id: 13,
      city: "Delhi",
      space_available: 654,
      type: "Leasable Space",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-1",
      code: "W-000014",
      id: 14,
      city: "Mumbai",
      space_available: 500,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-2",
      code: "W-000015",
      id: 15,
      city: "Bangalore",
      space_available: 1500,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-3",
      code: "W-000016",
      id: 16,
      city: "Chennai",
      space_available: 200,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-17",
      code: "W-000017",
      id: 17,
      city: "Delhi",
      space_available: 1234,
      type: "Leasable Space",
      cluster: "cluster-a-32",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-18",
      code: "W-000018",
      id: 18,
      city: "Chennai",
      space_available: 124,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-19",
      code: "W-000019",
      id: 19,
      city: "Indore",
      space_available: 134,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-20",
      code: "W-000020",
      id: 20,
      city: "Chennai",
      space_available: 12,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-21",
      code: "W-000021",
      id: 21,
      city: "Chennai",
      space_available: 1243434,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-22",
      code: "W-000022",
      id: 22,
      city: "Chennai",
      space_available: 1,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-23",
      code: "W-000023",
      id: 23,
      city: "Mumbai",
      space_available: 4,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-24",
      code: "W-000024",
      id: 24,
      city: "Bangalore",
      space_available: 3456,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-25",
      code: "W-000025",
      id: 25,
      city: "Bangalore",
      space_available: 1234545,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-26",
      code: "W-000026",
      id: 26,
      city: "Guwahati",
      space_available: 121234,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-27",
      code: "W-000027",
      id: 27,
      city: "Delhi",
      space_available: 98,
      type: "Leasable Space",
      cluster: "cluster-v-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-28",
      code: "W-000028",
      id: 28,
      city: "Indore",
      space_available: 97,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-29",
      code: "W-000029",
      id: 29,
      city: "Delhi",
      space_available: 654,
      type: "Leasable Space",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-30",
      code: "W-000030",
      id: 30,
      city: "Mumbai",
      space_available: 500,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-31",
      code: "W-000031",
      id: 31,
      city: "Bangalore",
      space_available: 1500,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-32",
      code: "W-000032",
      id: 32,
      city: "Chennai",
      space_available: 200,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-33",
      code: "W-000033",
      id: 33,
      city: "Delhi",
      space_available: 1234,
      type: "Leasable Space",
      cluster: "cluster-a-32",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-34",
      code: "W-000034",
      id: 34,
      city: "Chennai",
      space_available: 124,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-35",
      code: "W-000035",
      id: 35,
      city: "Indore",
      space_available: 134,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-36",
      code: "W-000036",
      id: 36,
      city: "Chennai",
      space_available: 12,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-37",
      code: "W-000037",
      id: 37,
      city: "Chennai",
      space_available: 1243434,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-38",
      code: "W-000038",
      id: 38,
      city: "Chennai",
      space_available: 1,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-39",
      code: "W-000039",
      id: 39,
      city: "Mumbai",
      space_available: 4,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-40",
      code: "W-000040",
      id: 40,
      city: "Bangalore",
      space_available: 3456,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-41",
      code: "W-000041",
      id: 41,
      city: "Bangalore",
      space_available: 1234545,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-42",
      code: "W-000042",
      id: 42,
      city: "Guwahati",
      space_available: 121234,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-43",
      code: "W-000043",
      id: 43,
      city: "Delhi",
      space_available: 98,
      type: "Leasable Space",
      cluster: "cluster-v-2",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-44",
      code: "W-000044",
      id: 44,
      city: "Indore",
      space_available: 97,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-45",
      code: "W-000045",
      id: 45,
      city: "Delhi",
      space_available: 654,
      type: "Leasable Space",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-46",
      code: "W-000046",
      id: 46,
      city: "Mumbai",
      space_available: 500,
      type: "Leasable Space",
      cluster: "cluster-a-2",
      is_registered: true,
      is_live: true,
    },
    {
      name: "Warehouse-Extra-47",
      code: "W-000047",
      id: 47,
      city: "Bangalore",
      space_available: 1500,
      type: "Warehouse Service",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-48",
      code: "W-000048",
      id: 48,
      city: "Chennai",
      space_available: 200,
      type: "Leasable Space",
      cluster: "cluster-a-21",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-49",
      code: "W-000049",
      id: 49,
      city: "Delhi",
      space_available: 1234,
      type: "Leasable Space",
      cluster: "cluster-a-32",
      is_registered: true,
      is_live: false,
    },
    {
      name: "Warehouse-Extra-50",
      code: "W-000050",
      id: 50,
      city: "Chennai",
      space_available: 124,
      type: "Warehouse Service",
      cluster: "cluster-a-1",
      is_registered: true,
      is_live: false,
    }
  ]